// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqpsvtulywmuoxczemoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcHN2dHVseXdtdW94Y3plbW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDc1NjcsImV4cCI6MjA2ODQyMzU2N30.6Cya0jUpu6rysbCadOPRh8qBiHzocTDNaXMfzEEg6Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});